title: Upterm
theme: jekyll-theme-midnight
description: Secure Terminal Sharing
show_downloads: true
google_analytics: UA-155365325-1
github:
    public: true
    is_project_page: true
    repository_url: https://github.com/jingweno/upterm
    repository_nwo: jingweno/upterm
    is_user_page: false
    owner_url: https://github.com/jingweno
    owner_name: jingweno
    zip_url: https://github.com/jingweno/upterm/releases
    tar_url: https://github.com/jingweno/upterm/releases
