{{- if .Values.websocket.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "upterm.fullname" . }}
  labels:
    {{- include "upterm.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.websocket.ingress_nginx_ingress_class }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    cert-manager.io/issuer: {{ include "upterm.fullname" . }}-letsencrypt
spec:
    tls:
      - hosts:
        - {{ .Values.websocket.host }}
        secretName: {{ .Values.websocket.host | replace "." "-" }}-tls
    rules:
      - host: {{ .Values.websocket.host }}
        http:
          paths:
          - backend:
              serviceName: {{ include "upterm.fullname" . }}
              servicePort: 80
{{- end }}
